In [3]:
# import libraries
from bs4 import BeautifulSoup
import requests
import time
import datetime
import smtplib

In [4]:
# connect to website

url = "https://www.amazon.com/Data-Analyst-Athletic-Lettering-Analysis/dp/B0FSTBDLLP/ref=sr_1_2_sspa?dib=eyJ2IjoiMSJ9.y-dKYAVXgWRVQBmP8DeltXRtJocF58yoqo8lRTYGNfSsuEe2Ohx9QDSmoMHze3gMNCCG4pSTIf6Y3EL1EThbApkBkwaoSslX3PGSpQDkIHiLt13mqHcqkFi9A4xXxGqqm1m2BgMFzO3s0x4gKKQGwNkPkHabuFu14sXd9hrSphO2c8KlCzOqPeU-w-y5u_9IIuxGZq__eKfFV_62_T4HeD0dmJMFC2UfgZ882sxmZHnL-uOEP5YnE3o7t5AONcmHw_Z7vjBBgduKhf50DUcalvTTqvw6lQ2TCgBO9PtLyqs.plweGNd6N-1LRxCnAQhXvQL0oHbtKgEi0Y1MsQ8FVLE&dib_tag=se&keywords=data%2Banalyst%2Btshirt&qid=1765918177&s=apparel&sr=1-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&customId=B0752XJYNL&customizationToken=MC_Assembly_1%23B0752XJYNL&th=1&psc=1"

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/127.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Referer": "https://www.google.com/",
    "Connection": "keep-alive",
}

# send request as if it's Chrome browser
page = requests.get(url, headers=headers)

In [5]:
soup1 = BeautifulSoup(page.content, 'html.parser') 

print(soup1)

<!DOCTYPE html>
<html class="a-no-js" data-19ax5a9jf="dingo" lang="en-us"><!-- sp:feature:head-start -->
<head><script>var aPageStart = (new Date()).getTime();</script><meta charset="utf-8"/>
<!-- sp:end-feature:head-start -->
<!-- sp:feature:csm:head-open-part1 -->
<script type="text/javascript">var ue_t0=ue_t0||+new Date();</script>
<!-- sp:end-feature:csm:head-open-part1 -->
<!-- sp:feature:cs-optimization -->
<meta content="on" http-equiv="x-dns-prefetch-control"/>
<link href="https://images-na.ssl-images-amazon.com" rel="dns-prefetch"/>
<link href="https://m.media-amazon.com" rel="dns-prefetch"/>
<link href="https://completion.amazon.com" rel="dns-prefetch"/>
<!-- sp:end-feature:cs-optimization -->
<!-- sp:feature:csm:head-open-part2 -->
<script type="text/javascript">
window.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;
if (window.ue_ihb === 1) {

var ue_csm = window,
    ue_hob = +new Date();
(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);


    var ue_err_chan = 'jserr-rw';
(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.location.href:"");b.logLevel=c;b.attribution=f.attribution||b.attribution;a.erl.push({ex:f,info:b})}}function l(a,b,c,e,g){d.ueLogError({m:a,f:b,l:c,c:""+e,err:g,fromOnError:1,args:arguments},g?{attribution:g.attribution,logLevel:g.logLevel}:void 0);return!1}var k="FATAL",m="ERROR",n="WARN",p="DOWNGRADED",a={ec:0,ecf:0,
pec:0,ts:0,erl:[],ter:[],buffer:[],mxe:50,startTimer:function(){a.ts++;setInterval(function(){d.ue&&a.pec<a.ec&&d.uex("at");a.pec=a.ec},1E4)}};l.skipTrace=1;h.skipTrace=1;h.isStub=1;d.ueLogError=h;d.ue_err=a;e.onerror=l})(ue_csm,window);


var ue_id = '0VKQMGPZAEJ5RVJDGR05',
    ue_url = '/rd/uedata',
    ue_drfp = true,
    ue_navtiming = 1,
    ue_mid = 'ATVPDKIKX0DER',
    ue_sid = '145-7402958-1189740',
    ue_sn = 'www.amazon.com',
    ue_furl = 'fls-na.amazon.com',
    ue_surl = 'https://unagi.amazon.com/1/events/com.amazon.csm.nexusclient.prod',
    ue_int = 0,
    ue_fcsn = 1,
    ue_urt = 3,
    ue_rpl_ns = 'cel-rpl',
    ue_ddq = 1,
    ue_fpf = '//fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:145-7402958-1189740:0VKQMGPZAEJ5RVJDGR05$uedata=s:',
    ue_sbuimp = 1,
    ue_ibft = 0,
    ue_fnt = 0,
    ue_lpsi = 6000,
    ue_lob = '1',
    ue_dsbl_cel = 1,

    ue_swi = 1;
var ue_viz=function(){(function(b,f,d){function g(){return(!(p in d)||0<d[p])&&(!(q in d)||0<d[q])}function h(c){if(b.ue.viz.length<w&&!r){var a=c.type;c=c.originalEvent;/^focus./.test(a)&&c&&(c.toElement||c.fromElement||c.relatedTarget)||(a=g()?f[s]||("blur"==a||"focusout"==a?t:u):t,b.ue.viz.push(a+":"+(+new Date-b.ue.t0)),a==u&&(b.ue.isl&&x("at"),r=1))}}for(var r=0,x=b.uex,a,k,l,s,v=["","webkit","o","ms","moz"],e=0,m=1,u="visible",t="hidden",p="innerWidth",q="innerHeight",w=20,n=0;n<v.length&&!e;n++)if(a=
v[n],k=(a?a+"H":"h")+"idden",e="boolean"==typeof f[k])l=a+"visibilitychange",s=(a?a+"V":"v")+"isibilityState";h({});e&&f.addEventListener(l,h,0);m=g()?1:0;d.addEventListener("resize",function(){var a=g()?1:0;m!==a&&(m=a,h({}))},{passive:!0});b.ue&&e&&(b.ue.pageViz={event:l,propHid:k})})(ue_csm,ue_csm.document,ue_csm.window)};window.ue_viz=ue_viz;

(function(d,h,O){function F(a){return a&&a.replace&&a.replace(/^\s+|\s+$/g,"")}function v(a){return"undefined"===typeof a}function D(a,b){for(var c in b)b[w](c)&&(a[c]=b[c])}function K(a){try{var b=O.cookie.match(RegExp("(^| )"+a+"=([^;]+)"));if(b)return b[2].trim()}catch(c){}}function P(m,b,c){var p=(B||{}).type;if("device"!==c||2!==p&&1!==p){if(m){d.ue_id=a.id=a.rid=m;if("device"===c||"pre-fetch"===c)a.oid=F(m);x&&(x=x.replace(/((.*?:){2})(\w+)/,function(a,b){return b+m}));G&&(e("id",G,m),G=0)}b&&
(x&&(x=x.replace(/(.*?:)(\w|-)+/,function(a,c){return c+b})),d.ue_sid=b);c&&a.tag("page-source:"+c);d.ue_fpf=x}}function Q(){var a={};return function(b){b&&(a[b]=1);b=[];for(var c in a)a[w](c)&&b.push(c);return b}}function C(d,b,c,p){p=p||+new H;var f,k;if(b||v(c)){if(d)for(k in f=b?e("t",b)||e("t",b,{}):a.t,f[d]=p,c)c[w](k)&&e(k,b,c[k]);return p}}function e(d,b,c){var e=b&&b!=a.id?a.sc[b]:a;e||(e=a.sc[b]={});"id"===d&&c&&(R=1);return e[d]=c||e[d]}function S(d,b,c,e,f){c="on"+c;var k=b[c];"function"===
typeof k?d&&(a.h[d]=k):k=function(){};b[c]=function(a){f?(e(a),k(a)):(k(a),e(a))};b[c]&&(b[c].isUeh=1)}function T(m,b,c,p){function q(b,c){var d=[b],g=0,f={},p,k;s.latency={};c?(d.push("m=1"),f[c]=1):f=a.sc;for(k in f)if(f[w](k)){var h=e("wb",k),l=e("t",k)||{},n=e("t0",k)||a.t0,q;if(c||2==h){h=h?g++:"";d.push("sc"+h+"="+k);for(q in l)v(l[q])||null===l[q]||d.push(q+h+"="+(l[q]-n));d.push("t"+h+"="+l[m]);s.latency["t"+h]=l[m];if(e("ctb",k)||e("wb",k))p=1}}!A&&p&&d.push("ctb=1");return d.join("&")}function k(b,
c,g,e,m){if(b){var f=d.ue_err;d.ue_url&&!d.ue_drfp&&!e&&!m&&b&&0<b.length&&(e=new Image,a.iel.push(e),e.src=b,a.count&&a.count("postbackImageSize",b.length));x?(m=h.encodeURIComponent)&&b&&(e=new Image,b=""+d.ue_fpf+m(b)+":"+(+new H-d.ue_t0),a.iel.push(e),e.src=b):a.log&&(a.log(b,"uedata",{n:1}),a.ielf.push(b));f&&!f.ts&&f.startTimer();a.b&&(f=a.b,a.b="",k(f,c,g,1))}}function r(b){var c=B?B.type:I,d=2==c||a.isBFonMshop,c=c&&!d,e=a.bfini;if(!R||a.isBFCache)e&&1<e&&(b+="&bfform=1",c||(a.isBFT=e-1)),
d&&(b+="&bfnt=1",a.isBFT=a.isBFT||1),a.ssw&&a.isBFT&&(a.isBFonMshop&&(a.isNRBF=0),v(a.isNRBF)&&(d=a.ssw(a.oid),d.e||v(d.val)||(a.isNRBF=1<d.val?0:1)),v(a.isNRBF)||(b+="&nrbf="+a.isNRBF)),a.isBFT&&!a.isNRBF&&(b+="&bft="+a.isBFT);return b}if(!a.paused&&(b||v(c))){for(var n in c)c[w](n)&&e(n,b,c[n]);a.isBFonMshop||C("pc",b,c);n="ld"===m&&b&&e("wb",b);var t=e("id",b)||a.id;n||t===a.oid||(G=b,ca(t,(e("t",b)||{}).tc||+e("t0",b),+e("t0",b),e("pty",b),e("spty",b)));var t=e("id",b)||a.id,u=e("id2",b),g=a.url+
"?"+m+"&v="+a.v+"&id="+t,A=e("ctb",b)||e("wb",b),s={eventName:m,version:a.v,id:t,sessionId:d.ue_sid||"",obfuscatedMarketplaceId:d.ue_mid||""},y;A&&(g+="&ctb="+A);u&&(g+="&id2="+u);1<d.ueinit&&(g+="&ic="+d.ueinit);if(!("ld"!=m&&"ul"!=m||b&&b!=t)){if("ld"==m){try{h[L]&&h[L].isUeh&&(h[L]=null)}catch(K){}if(h.chrome)for(u=0;u<M.length;u++)U(J,M[u]);(u=O.ue_backdetect)&&u.ue_back&&u.ue_back.value++;d._uess&&(y=d._uess());a.isl=1}a._bf&&(g+="&bf="+a._bf());d.ue_navtiming&&f&&(e("ctb",t,"1"),a.isBFonMshop||
C("tc",I,I,N));!E||a.isBFonMshop||V||(f&&D(a.t,{na_:f.navigationStart,ul_:f.unloadEventStart,_ul:f.unloadEventEnd,rd_:f.redirectStart,_rd:f.redirectEnd,fe_:f.fetchStart,lk_:f.domainLookupStart,_lk:f.domainLookupEnd,co_:f.connectStart,_co:f.connectEnd,sc_:f.secureConnectionStart,rq_:f.requestStart,rs_:f.responseStart,_rs:f.responseEnd,dl_:f.domLoading,di_:f.domInteractive,de_:f.domContentLoadedEventStart,_de:f.domContentLoadedEventEnd,_dc:f.domComplete,ld_:f.loadEventStart,_ld:f.loadEventEnd,ntd:("function"!==
typeof E.now||v(N)?0:new H(N+E.now())-new H)+a.t0}),B&&D(a.t,{ty:B.type+a.t0,rc:B.redirectCount+a.t0}),V=1);a.isBFonMshop||D(a.t,{hob:d.ue_hob,hoe:d.ue_hoe});a.ifr&&(g+="&ifr=1",s.ifr=!0)}C(m,b,c,p);var z,l;n||b&&b!==t||da(b);(c=d.ue_mbl)&&c.cnt&&!n&&(g+=c.cnt());n?e("wb",b,2):"ld"==m&&(a.lid=F(t));for(z in a.sc)if(1==e("wb",z))break;if(n){if(a.s)return;g=q(g,null)}else c=q(g,null),c!=g&&(c=r(c),a.b=c),y&&(g+=y),g=q(g,b||a.id);g=r(g);if(a.b||n)for(z in a.sc)2==e("wb",z)&&delete a.sc[z];z=0;a._rt&&
(g+="&rt="+a._rt());y=h.csa;if(!n&&y)for(l in c=e("t",b)||{},p=y("PageTiming"),c)c[w](l)&&p("mark",ea[l]||l,c[l]);n||(a.s=0,(l=d.ue_err)&&0<l.ec&&l.pec<l.ec&&(l.pec=l.ec,g+="&ec="+l.ec+"&ecf="+l.ecf),z=e("ctb",b),"ld"!==m||b||a.markers?a.markers&&a.isl&&!n&&b&&D(a.markers,e("t",b)):(a.markers={},D(a.markers,e("t",b))),e("t",b,{}));a.tag&&a.tag().length&&(g+="&csmtags="+a.tag().join("|"),s.csmtags=a.tag(),a.tag=Q());l=a.viz||[];if(c=l.length)l=l.splice(0,c),g+="&viz="+l.join("|"),s.viz=l;v(d.ue_pty)||
(g+="&pty="+d.ue_pty+"&spty="+d.ue_spty+"&pti="+d.ue_pti,s.pty=d.ue_pty,s.spty=d.ue_spty,s.pti=d.ue_pti);a.tabid&&(g+="&tid="+a.tabid);a.aftb&&(g+="&aftb=1");!a._ui||b&&b!=t||(g+=a._ui());g+="&lob="+(d.ue_lob||"0");a.a=g;k(g,m,z,n,b&&"string"===typeof b&&-1!==b.indexOf("csa:"));n||(s.lob=d.ue_lob||"0",(b=y&&y("UEData"))&&b("log",s))}}function da(a){var b=h.ue_csm_markers||{},c;for(c in b)b[w](c)&&C(c,a,I,b[c])}function A(a,b,c){c=c||h;if(c[W])c[W](a,b,!1);else if(c[X])c[X]("on"+a,b)}function U(a,
b,c){c=c||h;if(c[Y])c[Y](a,b,!1);else if(c[Z])c[Z]("on"+a,b)}function $(){function a(){d.onUl()}function b(a){return function(){c[a]||(c[a]=1,T(a))}}var c={},e,f;d.onLd=b("ld");d.onLdEnd=b("ld");d.onUl=b("ul");e={stop:b("os")};h.chrome?(A(J,a),M.push(a)):e[J]=d.onUl;for(f in e)e[w](f)&&S(0,h,f,e[f]);d.ue_viz&&ue_viz();A("load",d.onLd);C("ue")}function ca(e,b,c,f,q){var k=d.ue_mbl,r=h.csa,n=r&&r("SPA"),r=r&&r("PageTiming");k&&k.ajax&&k.ajax(b,c);n&&r&&(e={requestId:e,transitionType:"soft"},"string"===
typeof f&&(e.pageType=f,d.ue_pty=f),"string"===typeof q&&(e.subPageType=q,d.ue_spty=q),n("newPage",e),r("mark","transitionStart",b));a.tag("ajax-transition")}d.ueinit=(d.ueinit||0)+1;var a=d.ue=d.ue||{};a.t0=h.aPageStart||d.ue_t0;a.id=d.ue_id;a.url=d.ue_url;a.rid=d.ue_id;a.a="";a.b="";a.h={};a.s=1;a.t={};a.sc={};a.iel=[];a.ielf=[];a.viz=[];a.v="0.334294.0";a.paused=!1;var w="hasOwnProperty",J="beforeunload",L="on"+J,W="addEventListener",Y="removeEventListener",X="attachEvent",Z="detachEvent",ea={cf:"criticalFeature",
af:"aboveTheFold",fn:"functional",fp:"firstPaint",fcp:"firstContentfulPaint",bb:"bodyBegin",be:"bodyEnd",ld:"loaded"},H=h.Date,E=h.performance||h.webkitPerformance,f=(E||{}).timing,B=(E||{}).navigation,N=(f||{}).navigationStart,x=d.ue_fpf,R=0,V=0,M=[],G=0,I;a.oid=F(a.id);a.lid=F(a.id);a._t0=a.t0;a.tag=Q();a.ifr=h.top!==h.self||h.frameElement?1:0;a.markers=null;a.attach=A;a.detach=U;if("000-0000000-8675309"===d.ue_sid){var aa=K("cdn-rid"),ba=K("session-id");aa&&ba&&P(aa,ba,"cdn")}d.uei=$;d.ueh=S;d.ues=
e;d.uet=C;d.uex=T;a.reset=P;a.pause=function(d){a.paused=d};$()})(ue_csm,ue_csm.window,ue_csm.document);


ue.stub(ue,"event");ue.stub(ue,"onSushiUnload");ue.stub(ue,"onSushiFlush");

ue.stub(ue,"log");ue.stub(ue,"onunload");ue.stub(ue,"onflush");
(function(b){var a=b.ue;a.cv={};a.cv.scopes={};a.cv.buffer=[];a.count=function(b,d,c){var e=a.cv;a.d();c&&c.scope&&(e=a.cv.scopes[c.scope]=a.cv.scopes[c.scope]||{});if(void 0===d)return e[b];e[b]=d;a.cv.buffer.push({c:b,v:d})};a.count("baselineCounter2",1);a&&a.event&&(a.event({requestId:b.ue_id||"rid",server:b.ue_sn||"sn",obfuscatedMarketplaceId:b.ue_mid||"mid"},"csm","csm.CSMBaselineEvent.4"),a.count("nexusBaselineCounter",1,{bf:1}))})(ue_csm);



var ue_hoe = +new Date();
}
window.ueinit = window.ue_ihb;
</script>
<!-- eqb170rbakrp6aqcg9f7i8f88b4nc5ymm23u -->
<script>window.ue && ue.count && ue.count('CSMLibrarySize', 10344)</script>
<!-- sp:end-feature:csm:head-open-part2 -->
<!-- sp:feature:aui-assets -->
<link href="https://m.media-amazon.com/images/I/213sKsGm6jL._RC|51gj1xZyoqL.css_.css?AUIClients/AmazonUI" rel="stylesheet">
<link href="https://m.media-amazon.com/images/I/11T9EXq1JNL._RC|01cxwTawfML.css,41mvUzsVUUL.css,314EM8NicaL.css,21JMC7OC91L.css,01xH+fhFIJL.css,01EJgRrSvHL.css,413Vvv3GONL.css,1170nDgl0uL.css,01Rw4F+QU6L.css,016PR8+GNpL.css,11NeGmEx+fL.css,01LmAy9LJTL.css,01IdKcBuAdL.css,01iHqjS7YfL.css,01eVBHHaY+L.css,21XTBCXp9XL.css,11pDJV08stL.css,51deSG78a3L.css,01HWrzt-WgL.css,01XPHJk60-L.css,11aX6hlPzjL.css,01GAxF7K5tL.css,01ZM-s8Z3xL.css,21gEzBqpmtL.css,11CFYS0t4PL.css,21TxBPhrLyL.css,21Dt9D2TuML.css,31pv-avb0XL.css,111h7n9dRnL.css,31UjVzu+qrL.css,01BobvJ+BYL.css,11PDZ29p-PL.css,11kbPm9N5xL.css,215WpAjwzoL.css,11sUwulETuL.css,114aTS6SjML.css,01xFKTPySiL.css,21veZgndJZL.css,21OD8FuBraL.css,11XozyxiH7L.css,21OIIrnkCdL.css,11bW5bxACjL.css,119Cktja74L.css,11PMguLK6gL.css,01890+Vwk8L.css,11sjvwOAToL.css,01qiwJ7qDfL.css,21AS3Iv3HQL.css,016mfgi+D2L.css,01VinDhK+DL.css,31XjpIsCWeL.css,21msrr4h2yL.css,013-xYw+SRL.css_.css?AUIClients/AmazonUI#us.not-trident.1305099-T1.1288153-T2.1288171-T2.1343405-T1.1330429-T1" rel="stylesheet">
<link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/61xJcNKKLXL.js?AUIClients/AmazonUIjQuery" rel="preload">
<link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/11zuylp74DL._RC|11Y+5x+kkTL.js,51LPrROZ2JL.js,11EeeaacI2L.js,11GgN1+C7hL.js,01+z+uIeJ-L.js,01VRMV3FBdL.js,21NadQlXUWL.js,01vRf9id2EL.js,11a7qqY8xXL.js,11vhDGG+U+L.js,51C4kaFbiAL.js,11FhdH2HZwL.js,11wb9K3sw0L.js,11BrgrMAHUL.js,11GPhx42StL.js,210X-JWUe-L.js,01Svfxfy8OL.js,61uZ+hPSDZL.js,01ikBbTAneL.js,316JwWyajNL.js,01qXJuwGmxL.js,01WlsjNmqIL.js,11F929pmpYL.js,31vxRYDelFL.js,01rpauTep4L.js,31rqCOnXDNL.js,011FfPwYqHL.js,21XP+AHtinL.js,013ncka0wXL.js,21kN0q4IA-L.js,01VvIkYCafL.js,11vb6P5C5AL.js,01VMML3XPCL.js_.js?AUIClients/AmazonUI#372963-T1.1343405-T1.1330429-T1" rel="preload"/>
<link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/517f0agMn-L.js?AUIClients/CardJsRuntimeBuzzCopyBuild" rel="preload"/>
<script>
(function(b,a,c,d){if((b=b.AmazonUIPageJS||b.P)&&b.when&&b.register){c=[];for(a=a.currentScript;a;a=a.parentElement)a.id&&c.push(a.id);return b.log("A copy of P has already been loaded on this page.","FATAL",c.join(" "))}})(window,document,Date);(function(a,b,c,d){"use strict";a._pSetI=function(){return null}})(window,document,Date);(function(b,a,J,C){"use strict";b._pd=function(){var c,v;return function(D,e,g,h,d,E,w,F,G){function x(b){try{return b()}catch(K){return!1}}function p(c){return b.matchMedia?b.matchMedia(c):{matches:!1}}function k(){if(l){var y=c.mobile||c.tablet?q.matches&&m.matches:m.matches;if(z!==y){var a={w:b.innerWidth||d.clientWidth,h:b.innerHeight||d.clientHeight};if(17<Math.abs(r.w-a.w)||50<Math.abs(r.h-a.h))r=a,(z=y)?h(d,"a-ws"):d.className=w(d,"a-ws")}}}function H(b){(l=b===C?!l:!!b)&&k()}function I(){return l}
if(!v){v=!0;var t=function(){var b=["O","ms","Moz","Webkit"],c=a.createElement("div");return{testGradients:function(){return!0},test:function(a){var d=a.charAt(0).toUpperCase()+a.substr(1);a=(b.join(d+" ")+d+" "+a).split(" ");for(d=a.length;d--;)if(""===c.style[a[d]])return!0;return!1},testTransform3d:function(){return!0}}}();g=d.className;var A=/(^| )a-mobile( |$)/.test(g),B=/(^| )a-tablet( |$)/.test(g);c={audio:function(){return!!a.createElement("audio").canPlayType},video:function(){return!!a.createElement("video").canPlayType},
canvas:function(){return!!a.createElement("canvas").getContext},svg:function(){return!!a.createElementNS&&!!a.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},offline:function(){return navigator.hasOwnProperty&&navigator.hasOwnProperty("onLine")&&navigator.onLine},dragDrop:function(){return"draggable"in a.createElement("span")},geolocation:function(){return!!navigator.geolocation},history:function(){return!(!b.history||!b.history.pushState)},webworker:function(){return!!b.Worker},
autofocus:function(){return"autofocus"in a.createElement("input")},inputPlaceholder:function(){return"placeholder"in a.createElement("input")},textareaPlaceholder:function(){return"placeholder"in a.createElement("textarea")},localStorage:function(){return"localStorage"in b&&null!==b.localStorage},orientation:function(){return"orientation"in b},touch:function(){return"ontouchend"in a},gradients:function(){return t.testGradients()},hires:function(){var a=b.devicePixelRatio&&1.5<=b.devicePixelRatio||
b.matchMedia&&b.matchMedia("(min-resolution:144dpi)").matches;F("hiRes"+(A?"Mobile":B?"Tablet":"Desktop"),a?1:0);return a},transform3d:function(){return t.testTransform3d()},touchScrolling:function(){return e(/Windowshop|android|OS ([5-9]|[1-9][0-9]+)(_[0-9]{1,2})+ like Mac OS X|SOFTWARE=([5-9]|[1-9][0-9]+)(.[0-9]{1,2})+.*DEVICE=iPhone|Chrome|Silk|Firefox|Trident.+?; Touch/i)},ios:function(){return e(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!e(/trident|Edge/i)},android:function(){return e(/android.([1-9]|[L-Z])/i)&&
!e(/trident|Edge/i)},mobile:function(){return A},tablet:function(){return B},rtl:function(){return"rtl"===d.dir}};for(var f in c)c.hasOwnProperty(f)&&(c[f]=x(c[f]));for(var u="textShadow textStroke boxShadow borderRadius borderImage opacity transform transition".split(" "),n=0;n<u.length;n++)c[u[n]]=x(function(){return t.test(u[n])});var l=!0,r={w:0,h:0},q=p("(orientation:landscape)"),m=c.mobile||c.tablet?p("(min-width:451px)"):p("(min-width:1250px)");q.addListener&&q.addListener(k);m.addListener&&
m.addListener(k);var z;k();d.className=w(d,"a-no-js");h(d,"a-js");!e(/OS [1-8](_[0-9]*)+ like Mac OS X/i)||b.navigator.standalone||e(/safari/i)||h(d,"a-ember");g=[];for(f in c)c.hasOwnProperty(f)&&c[f]&&g.push("a-"+f.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()}));h(d,g.join(" "));d.setAttribute("data-aui-build-date",G);D.register("p-detect",function(){return{capabilities:c,localStorage:c.localStorage&&E,toggleResponsiveGrid:H,responsiveGridEnabled:I}});return c||{}}}}()})(window,document,
Date);(function(a,p,q,k){function m(e,b,c,g){a.P.when.apply(a.P,b).register("flow:"+e,function(){var a=g.apply(this,arguments);return c||a})}function l(e){a.P.log(e,"FATAL","AmazonUIPageJS@AUIDefineJS")}function f(a,b,c){Object.defineProperty(a,b,{value:c,writable:!1})}function n(e,b,c){"string"!==typeof e&&a.P.error("Anonymous modules are not supported.");var g=c!==k?c:"function"===typeof b?b:k;g||a.P.error("A callback must be provided");var f,h=[];if(c&&Array.isArray(b)&&(h=b.reduce(function(b,d){if("module"===
d||"require"===d)a.P.error('"module" or "require" injection is not supported.');else if("exports"===d){d=f={};var c="flow:"+e+"-exports";a.P.declare(c,d);b.push(c)}else 0!==d.lastIndexOf("@amzn/",0)?l("Dependency "+d+" does not begin with '@amzn/'"):b.push("flow:"+d);return b},[]),b.length!==h.length))return;m(e,h,f,g)}"use strict";Object.prototype.hasOwnProperty.call(a,"aui")?l("AUIDefineJS is already present globally"):(f(a,"aui",{}),f(a.aui,"amd_define",n))})(window,document,Date);(function(g,h,E,F){function N(a){l&&l.tag&&l.tag(p(":","aui",a))}function q(a,b){l&&l.count&&l.count("aui:"+a,0===b?0:b||(l.count("aui:"+a)||0)+1)}function O(a){try{return a.test(navigator.userAgent)}catch(b){return!1}}function x(a,b,d){a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,d)}function p(a,b,d,e){b=b&&d?b+a+d:b||d;return e?p(a,b,e):b}function y(a,b,d){try{Object.defineProperty(a,b,{value:d,writable:!1})}catch(e){a[b]=d}return d}function P(a,b){a.className=
Q(a,b)+" "+b}function Q(a,b){return(" "+a.className+" ").split(" "+b+" ").join(" ").replace(/^ | $/g,"")}function G(a){(a||[]).forEach(function(a){a in z||(z[a]=1,G(R[a]))})}function ea(a,b,d){var e=a.length,f=e,c=function(){f--||((d&&z.hasOwnProperty(d)?A:H).push(b),I||(m?m.set(B):setTimeout(B,0),I=!0))};for(c();e--;)S[a[e]]?c():(u[a[e]]=u[a[e]]||[]).push(c)}function fa(a,b,d,e,f){var c=h.createElement(a?"script":"link");x(c,"error",e);f&&x(c,"load",f);a?(c.type="text/javascript",c.async=!0,d&&/AUIClients|images[/]I/.test(b)&&
c.setAttribute("crossorigin","anonymous"),c.src=b):(c.rel="stylesheet",c.href=b);h.getElementsByTagName("head")[0].appendChild(c)}function T(a,b){return function(d,e){function f(){fa(b,d,c,function(b){J?q("resource_unload"):c?(c=!1,q("resource_retry"),f()):(q("resource_error"),a.log("Asset failed to load: "+d));b&&b.stopPropagation?b.stopPropagation():g.event&&(g.event.cancelBubble=!0)},e)}if(U[d])return!1;U[d]=!0;q("resource_count");var c=!0;return!f()}}function ha(a,b,d){for(var e={name:a,guard:function(c){return b.guardFatal(a,

In [6]:
soup2 = BeautifulSoup(soup1.prettify(), 'html.parser') 
print(soup2)

<!DOCTYPE html>

<html class="a-no-js" data-19ax5a9jf="dingo" lang="en-us">
<!-- sp:feature:head-start -->
<head>
<script>
   var aPageStart = (new Date()).getTime();
  </script>
<meta charset="utf-8"/>
<!-- sp:end-feature:head-start -->
<!-- sp:feature:csm:head-open-part1 -->
<script type="text/javascript">
   var ue_t0=ue_t0||+new Date();
  </script>
<!-- sp:end-feature:csm:head-open-part1 -->
<!-- sp:feature:cs-optimization -->
<meta content="on" http-equiv="x-dns-prefetch-control"/>
<link href="https://images-na.ssl-images-amazon.com" rel="dns-prefetch"/>
<link href="https://m.media-amazon.com" rel="dns-prefetch"/>
<link href="https://completion.amazon.com" rel="dns-prefetch"/>
<!-- sp:end-feature:cs-optimization -->
<!-- sp:feature:csm:head-open-part2 -->
<script type="text/javascript">
   window.ue_ihb = (window.ue_ihb || window.ueinit || 0) + 1;
if (window.ue_ihb === 1) {

var ue_csm = window,
    ue_hob = +new Date();
(function(d){var e=d.ue=d.ue||{},f=Date.now||function(){return+new Date};e.d=function(b){return f()-(b?0:d.ue_t0)};e.stub=function(b,a){if(!b[a]){var c=[];b[a]=function(){c.push([c.slice.call(arguments),e.d(),d.ue_id])};b[a].replay=function(b){for(var a;a=c.shift();)b(a[0],a[1],a[2])};b[a].isStub=1}};e.exec=function(b,a){return function(){try{return b.apply(this,arguments)}catch(c){ueLogError(c,{attribution:a||"undefined",logLevel:"WARN"})}}}})(ue_csm);


    var ue_err_chan = 'jserr-rw';
(function(d,e){function h(f,b){if(!(a.ec>a.mxe)&&f){a.ter.push(f);b=b||{};var c=f.logLevel||b.logLevel;c&&c!==k&&c!==m&&c!==n&&c!==p||a.ec++;c&&c!=k||a.ecf++;b.pageURL=""+(e.location?e.location.href:"");b.logLevel=c;b.attribution=f.attribution||b.attribution;a.erl.push({ex:f,info:b})}}function l(a,b,c,e,g){d.ueLogError({m:a,f:b,l:c,c:""+e,err:g,fromOnError:1,args:arguments},g?{attribution:g.attribution,logLevel:g.logLevel}:void 0);return!1}var k="FATAL",m="ERROR",n="WARN",p="DOWNGRADED",a={ec:0,ecf:0,
pec:0,ts:0,erl:[],ter:[],buffer:[],mxe:50,startTimer:function(){a.ts++;setInterval(function(){d.ue&&a.pec<a.ec&&d.uex("at");a.pec=a.ec},1E4)}};l.skipTrace=1;h.skipTrace=1;h.isStub=1;d.ueLogError=h;d.ue_err=a;e.onerror=l})(ue_csm,window);


var ue_id = '0VKQMGPZAEJ5RVJDGR05',
    ue_url = '/rd/uedata',
    ue_drfp = true,
    ue_navtiming = 1,
    ue_mid = 'ATVPDKIKX0DER',
    ue_sid = '145-7402958-1189740',
    ue_sn = 'www.amazon.com',
    ue_furl = 'fls-na.amazon.com',
    ue_surl = 'https://unagi.amazon.com/1/events/com.amazon.csm.nexusclient.prod',
    ue_int = 0,
    ue_fcsn = 1,
    ue_urt = 3,
    ue_rpl_ns = 'cel-rpl',
    ue_ddq = 1,
    ue_fpf = '//fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:145-7402958-1189740:0VKQMGPZAEJ5RVJDGR05$uedata=s:',
    ue_sbuimp = 1,
    ue_ibft = 0,
    ue_fnt = 0,
    ue_lpsi = 6000,
    ue_lob = '1',
    ue_dsbl_cel = 1,

    ue_swi = 1;
var ue_viz=function(){(function(b,f,d){function g(){return(!(p in d)||0<d[p])&&(!(q in d)||0<d[q])}function h(c){if(b.ue.viz.length<w&&!r){var a=c.type;c=c.originalEvent;/^focus./.test(a)&&c&&(c.toElement||c.fromElement||c.relatedTarget)||(a=g()?f[s]||("blur"==a||"focusout"==a?t:u):t,b.ue.viz.push(a+":"+(+new Date-b.ue.t0)),a==u&&(b.ue.isl&&x("at"),r=1))}}for(var r=0,x=b.uex,a,k,l,s,v=["","webkit","o","ms","moz"],e=0,m=1,u="visible",t="hidden",p="innerWidth",q="innerHeight",w=20,n=0;n<v.length&&!e;n++)if(a=
v[n],k=(a?a+"H":"h")+"idden",e="boolean"==typeof f[k])l=a+"visibilitychange",s=(a?a+"V":"v")+"isibilityState";h({});e&&f.addEventListener(l,h,0);m=g()?1:0;d.addEventListener("resize",function(){var a=g()?1:0;m!==a&&(m=a,h({}))},{passive:!0});b.ue&&e&&(b.ue.pageViz={event:l,propHid:k})})(ue_csm,ue_csm.document,ue_csm.window)};window.ue_viz=ue_viz;

(function(d,h,O){function F(a){return a&&a.replace&&a.replace(/^\s+|\s+$/g,"")}function v(a){return"undefined"===typeof a}function D(a,b){for(var c in b)b[w](c)&&(a[c]=b[c])}function K(a){try{var b=O.cookie.match(RegExp("(^| )"+a+"=([^;]+)"));if(b)return b[2].trim()}catch(c){}}function P(m,b,c){var p=(B||{}).type;if("device"!==c||2!==p&&1!==p){if(m){d.ue_id=a.id=a.rid=m;if("device"===c||"pre-fetch"===c)a.oid=F(m);x&&(x=x.replace(/((.*?:){2})(\w+)/,function(a,b){return b+m}));G&&(e("id",G,m),G=0)}b&&
(x&&(x=x.replace(/(.*?:)(\w|-)+/,function(a,c){return c+b})),d.ue_sid=b);c&&a.tag("page-source:"+c);d.ue_fpf=x}}function Q(){var a={};return function(b){b&&(a[b]=1);b=[];for(var c in a)a[w](c)&&b.push(c);return b}}function C(d,b,c,p){p=p||+new H;var f,k;if(b||v(c)){if(d)for(k in f=b?e("t",b)||e("t",b,{}):a.t,f[d]=p,c)c[w](k)&&e(k,b,c[k]);return p}}function e(d,b,c){var e=b&&b!=a.id?a.sc[b]:a;e||(e=a.sc[b]={});"id"===d&&c&&(R=1);return e[d]=c||e[d]}function S(d,b,c,e,f){c="on"+c;var k=b[c];"function"===
typeof k?d&&(a.h[d]=k):k=function(){};b[c]=function(a){f?(e(a),k(a)):(k(a),e(a))};b[c]&&(b[c].isUeh=1)}function T(m,b,c,p){function q(b,c){var d=[b],g=0,f={},p,k;s.latency={};c?(d.push("m=1"),f[c]=1):f=a.sc;for(k in f)if(f[w](k)){var h=e("wb",k),l=e("t",k)||{},n=e("t0",k)||a.t0,q;if(c||2==h){h=h?g++:"";d.push("sc"+h+"="+k);for(q in l)v(l[q])||null===l[q]||d.push(q+h+"="+(l[q]-n));d.push("t"+h+"="+l[m]);s.latency["t"+h]=l[m];if(e("ctb",k)||e("wb",k))p=1}}!A&&p&&d.push("ctb=1");return d.join("&")}function k(b,
c,g,e,m){if(b){var f=d.ue_err;d.ue_url&&!d.ue_drfp&&!e&&!m&&b&&0<b.length&&(e=new Image,a.iel.push(e),e.src=b,a.count&&a.count("postbackImageSize",b.length));x?(m=h.encodeURIComponent)&&b&&(e=new Image,b=""+d.ue_fpf+m(b)+":"+(+new H-d.ue_t0),a.iel.push(e),e.src=b):a.log&&(a.log(b,"uedata",{n:1}),a.ielf.push(b));f&&!f.ts&&f.startTimer();a.b&&(f=a.b,a.b="",k(f,c,g,1))}}function r(b){var c=B?B.type:I,d=2==c||a.isBFonMshop,c=c&&!d,e=a.bfini;if(!R||a.isBFCache)e&&1<e&&(b+="&bfform=1",c||(a.isBFT=e-1)),
d&&(b+="&bfnt=1",a.isBFT=a.isBFT||1),a.ssw&&a.isBFT&&(a.isBFonMshop&&(a.isNRBF=0),v(a.isNRBF)&&(d=a.ssw(a.oid),d.e||v(d.val)||(a.isNRBF=1<d.val?0:1)),v(a.isNRBF)||(b+="&nrbf="+a.isNRBF)),a.isBFT&&!a.isNRBF&&(b+="&bft="+a.isBFT);return b}if(!a.paused&&(b||v(c))){for(var n in c)c[w](n)&&e(n,b,c[n]);a.isBFonMshop||C("pc",b,c);n="ld"===m&&b&&e("wb",b);var t=e("id",b)||a.id;n||t===a.oid||(G=b,ca(t,(e("t",b)||{}).tc||+e("t0",b),+e("t0",b),e("pty",b),e("spty",b)));var t=e("id",b)||a.id,u=e("id2",b),g=a.url+
"?"+m+"&v="+a.v+"&id="+t,A=e("ctb",b)||e("wb",b),s={eventName:m,version:a.v,id:t,sessionId:d.ue_sid||"",obfuscatedMarketplaceId:d.ue_mid||""},y;A&&(g+="&ctb="+A);u&&(g+="&id2="+u);1<d.ueinit&&(g+="&ic="+d.ueinit);if(!("ld"!=m&&"ul"!=m||b&&b!=t)){if("ld"==m){try{h[L]&&h[L].isUeh&&(h[L]=null)}catch(K){}if(h.chrome)for(u=0;u<M.length;u++)U(J,M[u]);(u=O.ue_backdetect)&&u.ue_back&&u.ue_back.value++;d._uess&&(y=d._uess());a.isl=1}a._bf&&(g+="&bf="+a._bf());d.ue_navtiming&&f&&(e("ctb",t,"1"),a.isBFonMshop||
C("tc",I,I,N));!E||a.isBFonMshop||V||(f&&D(a.t,{na_:f.navigationStart,ul_:f.unloadEventStart,_ul:f.unloadEventEnd,rd_:f.redirectStart,_rd:f.redirectEnd,fe_:f.fetchStart,lk_:f.domainLookupStart,_lk:f.domainLookupEnd,co_:f.connectStart,_co:f.connectEnd,sc_:f.secureConnectionStart,rq_:f.requestStart,rs_:f.responseStart,_rs:f.responseEnd,dl_:f.domLoading,di_:f.domInteractive,de_:f.domContentLoadedEventStart,_de:f.domContentLoadedEventEnd,_dc:f.domComplete,ld_:f.loadEventStart,_ld:f.loadEventEnd,ntd:("function"!==
typeof E.now||v(N)?0:new H(N+E.now())-new H)+a.t0}),B&&D(a.t,{ty:B.type+a.t0,rc:B.redirectCount+a.t0}),V=1);a.isBFonMshop||D(a.t,{hob:d.ue_hob,hoe:d.ue_hoe});a.ifr&&(g+="&ifr=1",s.ifr=!0)}C(m,b,c,p);var z,l;n||b&&b!==t||da(b);(c=d.ue_mbl)&&c.cnt&&!n&&(g+=c.cnt());n?e("wb",b,2):"ld"==m&&(a.lid=F(t));for(z in a.sc)if(1==e("wb",z))break;if(n){if(a.s)return;g=q(g,null)}else c=q(g,null),c!=g&&(c=r(c),a.b=c),y&&(g+=y),g=q(g,b||a.id);g=r(g);if(a.b||n)for(z in a.sc)2==e("wb",z)&&delete a.sc[z];z=0;a._rt&&
(g+="&rt="+a._rt());y=h.csa;if(!n&&y)for(l in c=e("t",b)||{},p=y("PageTiming"),c)c[w](l)&&p("mark",ea[l]||l,c[l]);n||(a.s=0,(l=d.ue_err)&&0<l.ec&&l.pec<l.ec&&(l.pec=l.ec,g+="&ec="+l.ec+"&ecf="+l.ecf),z=e("ctb",b),"ld"!==m||b||a.markers?a.markers&&a.isl&&!n&&b&&D(a.markers,e("t",b)):(a.markers={},D(a.markers,e("t",b))),e("t",b,{}));a.tag&&a.tag().length&&(g+="&csmtags="+a.tag().join("|"),s.csmtags=a.tag(),a.tag=Q());l=a.viz||[];if(c=l.length)l=l.splice(0,c),g+="&viz="+l.join("|"),s.viz=l;v(d.ue_pty)||
(g+="&pty="+d.ue_pty+"&spty="+d.ue_spty+"&pti="+d.ue_pti,s.pty=d.ue_pty,s.spty=d.ue_spty,s.pti=d.ue_pti);a.tabid&&(g+="&tid="+a.tabid);a.aftb&&(g+="&aftb=1");!a._ui||b&&b!=t||(g+=a._ui());g+="&lob="+(d.ue_lob||"0");a.a=g;k(g,m,z,n,b&&"string"===typeof b&&-1!==b.indexOf("csa:"));n||(s.lob=d.ue_lob||"0",(b=y&&y("UEData"))&&b("log",s))}}function da(a){var b=h.ue_csm_markers||{},c;for(c in b)b[w](c)&&C(c,a,I,b[c])}function A(a,b,c){c=c||h;if(c[W])c[W](a,b,!1);else if(c[X])c[X]("on"+a,b)}function U(a,
b,c){c=c||h;if(c[Y])c[Y](a,b,!1);else if(c[Z])c[Z]("on"+a,b)}function $(){function a(){d.onUl()}function b(a){return function(){c[a]||(c[a]=1,T(a))}}var c={},e,f;d.onLd=b("ld");d.onLdEnd=b("ld");d.onUl=b("ul");e={stop:b("os")};h.chrome?(A(J,a),M.push(a)):e[J]=d.onUl;for(f in e)e[w](f)&&S(0,h,f,e[f]);d.ue_viz&&ue_viz();A("load",d.onLd);C("ue")}function ca(e,b,c,f,q){var k=d.ue_mbl,r=h.csa,n=r&&r("SPA"),r=r&&r("PageTiming");k&&k.ajax&&k.ajax(b,c);n&&r&&(e={requestId:e,transitionType:"soft"},"string"===
typeof f&&(e.pageType=f,d.ue_pty=f),"string"===typeof q&&(e.subPageType=q,d.ue_spty=q),n("newPage",e),r("mark","transitionStart",b));a.tag("ajax-transition")}d.ueinit=(d.ueinit||0)+1;var a=d.ue=d.ue||{};a.t0=h.aPageStart||d.ue_t0;a.id=d.ue_id;a.url=d.ue_url;a.rid=d.ue_id;a.a="";a.b="";a.h={};a.s=1;a.t={};a.sc={};a.iel=[];a.ielf=[];a.viz=[];a.v="0.334294.0";a.paused=!1;var w="hasOwnProperty",J="beforeunload",L="on"+J,W="addEventListener",Y="removeEventListener",X="attachEvent",Z="detachEvent",ea={cf:"criticalFeature",
af:"aboveTheFold",fn:"functional",fp:"firstPaint",fcp:"firstContentfulPaint",bb:"bodyBegin",be:"bodyEnd",ld:"loaded"},H=h.Date,E=h.performance||h.webkitPerformance,f=(E||{}).timing,B=(E||{}).navigation,N=(f||{}).navigationStart,x=d.ue_fpf,R=0,V=0,M=[],G=0,I;a.oid=F(a.id);a.lid=F(a.id);a._t0=a.t0;a.tag=Q();a.ifr=h.top!==h.self||h.frameElement?1:0;a.markers=null;a.attach=A;a.detach=U;if("000-0000000-8675309"===d.ue_sid){var aa=K("cdn-rid"),ba=K("session-id");aa&&ba&&P(aa,ba,"cdn")}d.uei=$;d.ueh=S;d.ues=
e;d.uet=C;d.uex=T;a.reset=P;a.pause=function(d){a.paused=d};$()})(ue_csm,ue_csm.window,ue_csm.document);


ue.stub(ue,"event");ue.stub(ue,"onSushiUnload");ue.stub(ue,"onSushiFlush");

ue.stub(ue,"log");ue.stub(ue,"onunload");ue.stub(ue,"onflush");
(function(b){var a=b.ue;a.cv={};a.cv.scopes={};a.cv.buffer=[];a.count=function(b,d,c){var e=a.cv;a.d();c&&c.scope&&(e=a.cv.scopes[c.scope]=a.cv.scopes[c.scope]||{});if(void 0===d)return e[b];e[b]=d;a.cv.buffer.push({c:b,v:d})};a.count("baselineCounter2",1);a&&a.event&&(a.event({requestId:b.ue_id||"rid",server:b.ue_sn||"sn",obfuscatedMarketplaceId:b.ue_mid||"mid"},"csm","csm.CSMBaselineEvent.4"),a.count("nexusBaselineCounter",1,{bf:1}))})(ue_csm);



var ue_hoe = +new Date();
}
window.ueinit = window.ue_ihb;
  </script>
<!-- eqb170rbakrp6aqcg9f7i8f88b4nc5ymm23u -->
<script>
   window.ue && ue.count && ue.count('CSMLibrarySize', 10344)
  </script>
<!-- sp:end-feature:csm:head-open-part2 -->
<!-- sp:feature:aui-assets -->
<link href="https://m.media-amazon.com/images/I/213sKsGm6jL._RC|51gj1xZyoqL.css_.css?AUIClients/AmazonUI" rel="stylesheet"/>
<link href="https://m.media-amazon.com/images/I/11T9EXq1JNL._RC|01cxwTawfML.css,41mvUzsVUUL.css,314EM8NicaL.css,21JMC7OC91L.css,01xH+fhFIJL.css,01EJgRrSvHL.css,413Vvv3GONL.css,1170nDgl0uL.css,01Rw4F+QU6L.css,016PR8+GNpL.css,11NeGmEx+fL.css,01LmAy9LJTL.css,01IdKcBuAdL.css,01iHqjS7YfL.css,01eVBHHaY+L.css,21XTBCXp9XL.css,11pDJV08stL.css,51deSG78a3L.css,01HWrzt-WgL.css,01XPHJk60-L.css,11aX6hlPzjL.css,01GAxF7K5tL.css,01ZM-s8Z3xL.css,21gEzBqpmtL.css,11CFYS0t4PL.css,21TxBPhrLyL.css,21Dt9D2TuML.css,31pv-avb0XL.css,111h7n9dRnL.css,31UjVzu+qrL.css,01BobvJ+BYL.css,11PDZ29p-PL.css,11kbPm9N5xL.css,215WpAjwzoL.css,11sUwulETuL.css,114aTS6SjML.css,01xFKTPySiL.css,21veZgndJZL.css,21OD8FuBraL.css,11XozyxiH7L.css,21OIIrnkCdL.css,11bW5bxACjL.css,119Cktja74L.css,11PMguLK6gL.css,01890+Vwk8L.css,11sjvwOAToL.css,01qiwJ7qDfL.css,21AS3Iv3HQL.css,016mfgi+D2L.css,01VinDhK+DL.css,31XjpIsCWeL.css,21msrr4h2yL.css,013-xYw+SRL.css_.css?AUIClients/AmazonUI#us.not-trident.1305099-T1.1288153-T2.1288171-T2.1343405-T1.1330429-T1" rel="stylesheet"/>
<link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/61xJcNKKLXL.js?AUIClients/AmazonUIjQuery" rel="preload"/>
<link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/11zuylp74DL._RC|11Y+5x+kkTL.js,51LPrROZ2JL.js,11EeeaacI2L.js,11GgN1+C7hL.js,01+z+uIeJ-L.js,01VRMV3FBdL.js,21NadQlXUWL.js,01vRf9id2EL.js,11a7qqY8xXL.js,11vhDGG+U+L.js,51C4kaFbiAL.js,11FhdH2HZwL.js,11wb9K3sw0L.js,11BrgrMAHUL.js,11GPhx42StL.js,210X-JWUe-L.js,01Svfxfy8OL.js,61uZ+hPSDZL.js,01ikBbTAneL.js,316JwWyajNL.js,01qXJuwGmxL.js,01WlsjNmqIL.js,11F929pmpYL.js,31vxRYDelFL.js,01rpauTep4L.js,31rqCOnXDNL.js,011FfPwYqHL.js,21XP+AHtinL.js,013ncka0wXL.js,21kN0q4IA-L.js,01VvIkYCafL.js,11vb6P5C5AL.js,01VMML3XPCL.js_.js?AUIClients/AmazonUI#372963-T1.1343405-T1.1330429-T1" rel="preload">
<link as="script" crossorigin="anonymous" href="https://m.media-amazon.com/images/I/517f0agMn-L.js?AUIClients/CardJsRuntimeBuzzCopyBuild" rel="preload">
<script>
      (function(b,a,c,d){if((b=b.AmazonUIPageJS||b.P)&&b.when&&b.register){c=[];for(a=a.currentScript;a;a=a.parentElement)a.id&&c.push(a.id);return b.log("A copy of P has already been loaded on this page.","FATAL",c.join(" "))}})(window,document,Date);(function(a,b,c,d){"use strict";a._pSetI=function(){return null}})(window,document,Date);(function(b,a,J,C){"use strict";b._pd=function(){var c,v;return function(D,e,g,h,d,E,w,F,G){function x(b){try{return b()}catch(K){return!1}}function p(c){return b.matchMedia?b.matchMedia(c):{matches:!1}}function k(){if(l){var y=c.mobile||c.tablet?q.matches&&m.matches:m.matches;if(z!==y){var a={w:b.innerWidth||d.clientWidth,h:b.innerHeight||d.clientHeight};if(17<Math.abs(r.w-a.w)||50<Math.abs(r.h-a.h))r=a,(z=y)?h(d,"a-ws"):d.className=w(d,"a-ws")}}}function H(b){(l=b===C?!l:!!b)&&k()}function I(){return l}
if(!v){v=!0;var t=function(){var b=["O","ms","Moz","Webkit"],c=a.createElement("div");return{testGradients:function(){return!0},test:function(a){var d=a.charAt(0).toUpperCase()+a.substr(1);a=(b.join(d+" ")+d+" "+a).split(" ");for(d=a.length;d--;)if(""===c.style[a[d]])return!0;return!1},testTransform3d:function(){return!0}}}();g=d.className;var A=/(^| )a-mobile( |$)/.test(g),B=/(^| )a-tablet( |$)/.test(g);c={audio:function(){return!!a.createElement("audio").canPlayType},video:function(){return!!a.createElement("video").canPlayType},
canvas:function(){return!!a.createElement("canvas").getContext},svg:function(){return!!a.createElementNS&&!!a.createElementNS("http://www.w3.org/2000/svg","svg").createSVGRect},offline:function(){return navigator.hasOwnProperty&&navigator.hasOwnProperty("onLine")&&navigator.onLine},dragDrop:function(){return"draggable"in a.createElement("span")},geolocation:function(){return!!navigator.geolocation},history:function(){return!(!b.history||!b.history.pushState)},webworker:function(){return!!b.Worker},
autofocus:function(){return"autofocus"in a.createElement("input")},inputPlaceholder:function(){return"placeholder"in a.createElement("input")},textareaPlaceholder:function(){return"placeholder"in a.createElement("textarea")},localStorage:function(){return"localStorage"in b&&null!==b.localStorage},orientation:function(){return"orientation"in b},touch:function(){return"ontouchend"in a},gradients:function(){return t.testGradients()},hires:function(){var a=b.devicePixelRatio&&1.5<=b.devicePixelRatio||
b.matchMedia&&b.matchMedia("(min-resolution:144dpi)").matches;F("hiRes"+(A?"Mobile":B?"Tablet":"Desktop"),a?1:0);return a},transform3d:function(){return t.testTransform3d()},touchScrolling:function(){return e(/Windowshop|android|OS ([5-9]|[1-9][0-9]+)(_[0-9]{1,2})+ like Mac OS X|SOFTWARE=([5-9]|[1-9][0-9]+)(.[0-9]{1,2})+.*DEVICE=iPhone|Chrome|Silk|Firefox|Trident.+?; Touch/i)},ios:function(){return e(/OS [1-9][0-9]*(_[0-9]*)+ like Mac OS X/i)&&!e(/trident|Edge/i)},android:function(){return e(/android.([1-9]|[L-Z])/i)&&
!e(/trident|Edge/i)},mobile:function(){return A},tablet:function(){return B},rtl:function(){return"rtl"===d.dir}};for(var f in c)c.hasOwnProperty(f)&&(c[f]=x(c[f]));for(var u="textShadow textStroke boxShadow borderRadius borderImage opacity transform transition".split(" "),n=0;n<u.length;n++)c[u[n]]=x(function(){return t.test(u[n])});var l=!0,r={w:0,h:0},q=p("(orientation:landscape)"),m=c.mobile||c.tablet?p("(min-width:451px)"):p("(min-width:1250px)");q.addListener&&q.addListener(k);m.addListener&&
m.addListener(k);var z;k();d.className=w(d,"a-no-js");h(d,"a-js");!e(/OS [1-8](_[0-9]*)+ like Mac OS X/i)||b.navigator.standalone||e(/safari/i)||h(d,"a-ember");g=[];for(f in c)c.hasOwnProperty(f)&&c[f]&&g.push("a-"+f.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()}));h(d,g.join(" "));d.setAttribute("data-aui-build-date",G);D.register("p-detect",function(){return{capabilities:c,localStorage:c.localStorage&&E,toggleResponsiveGrid:H,responsiveGridEnabled:I}});return c||{}}}}()})(window,document,
Date);(function(a,p,q,k){function m(e,b,c,g){a.P.when.apply(a.P,b).register("flow:"+e,function(){var a=g.apply(this,arguments);return c||a})}function l(e){a.P.log(e,"FATAL","AmazonUIPageJS@AUIDefineJS")}function f(a,b,c){Object.defineProperty(a,b,{value:c,writable:!1})}function n(e,b,c){"string"!==typeof e&&a.P.error("Anonymous modules are not supported.");var g=c!==k?c:"function"===typeof b?b:k;g||a.P.error("A callback must be provided");var f,h=[];if(c&&Array.isArray(b)&&(h=b.reduce(function(b,d){if("module"===
d||"require"===d)a.P.error('"module" or "require" injection is not supported.');else if("exports"===d){d=f={};var c="flow:"+e+"-exports";a.P.declare(c,d);b.push(c)}else 0!==d.lastIndexOf("@amzn/",0)?l("Dependency "+d+" does not begin with '@amzn/'"):b.push("flow:"+d);return b},[]),b.length!==h.length))return;m(e,h,f,g)}"use strict";Object.prototype.hasOwnProperty.call(a,"aui")?l("AUIDefineJS is already present globally"):(f(a,"aui",{}),f(a.aui,"amd_define",n))})(window,document,Date);(function(g,h,E,F){function N(a){l&&l.tag&&l.tag(p(":","aui",a))}function q(a,b){l&&l.count&&l.count("aui:"+a,0===b?0:b||(l.count("aui:"+a)||0)+1)}function O(a){try{return a.test(navigator.userAgent)}catch(b){return!1}}function x(a,b,d){a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,d)}function p(a,b,d,e){b=b&&d?b+a+d:b||d;return e?p(a,b,e):b}function y(a,b,d){try{Object.defineProperty(a,b,{value:d,writable:!1})}catch(e){a[b]=d}return d}function P(a,b){a.className=
Q(a,b)+" "+b}function Q(a,b){return(" "+a.className+" ").split(" "+b+" ").join(" ").replace(/^ | $/g,"")}function G(a){(a||[]).forEach(function(a){a in z||(z[a]=1,G(R[a]))})}function ea(a,b,d){var e=a.length,f=e,c=function(){f--||((d&&z.hasOwnProperty(d)?A:H).push(b),I||(m?m.set(B):setTimeout(B,0),I=!0))};for(c();e--;)S[a[e]]?c():(u[a[e]]=u[a[e]]||[]).push(c)}function fa(a,b,d,e,f){var c=h.createElement(a?"script":"link");x(c,"error",e);f&&x(c,"load",f);a?(c.type="text/javascript",c.async=!0,d&&/AUIClients|images[/]I/.test(b)&&
c.setAttribute("crossorigin","anonymous"),c.src=b):(c.rel="stylesheet",c.href=b);h.getElementsByTagName("head")[0].appendChild(c)}function T(a,b){return function(d,e){function f(){fa(b,d,c,function(b){J?q("resource_unload"):c?(c=!1,q("resource_retry"),f()):(q("resource_error"),a.log("Asset failed to load: "+d));b&&b.stopPropagation?b.stopPropagation():g.event&&(g.event.cancelBubble=!0)},e)}if(U[d])return!1;U[d]=!0;q("resource_count");var c=!0;return!f()}}function ha(a,b,d){for(var e={name:a,guard:function(c){return b.guardFatal(a,

In [7]:
title = soup2.find('span', id = 'productTitle').text

print(title)

                 Data Analyst Funny Athletic Lettering Data Analysis Gifts T-Shirt

In [8]:
price = soup2.find(class_ = 'a-price-whole').text
print(price)

                   28,611

                    .

In [9]:
price = price.replace('\n', '').replace('\t', '').replace(',', '').strip()
title = title.strip()

print(price)
print(title)

28611                                       .
Data Analyst Funny Athletic Lettering Data Analysis Gifts T-Shirt

In [4]:
from datetime import date

today = date.today()
print(today)

2026-05-12

In [11]:
import csv

header = ['Title', 'Price','Date']
data  = [title, price, today]

with open('AmazonWebscraperDataset.csv', 'w', newline = '', encoding = 'UTF8')  as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerow(data)

In [14]:
import pandas as pd

df = pd.read_csv(r"C:\Users\HP\AmazonWebscraperDataset.csv")
df

,Title,Price,Date
0,Data Analyst Funny Athletic Lettering Data Ana...,28611 .,2026-01-05
1,Data Analyst Funny Athletic Lettering Data Ana...,28611 .,2026-01-05

In [13]:
# Now we are appending data to the csv

with open('AmazonWebscraperDataset.csv', 'a+', newline = '', encoding = 'UTF8')  as f:
    writer = csv.writer(f)
    writer.writerow(data)

In [15]:
def check_price():
    url = "https://www.amazon.com/Data-Analyst-Athletic-Lettering-Analysis/dp/B0FSTBDLLP/ref=sr_1_2_sspa?dib=eyJ2IjoiMSJ9.y-dKYAVXgWRVQBmP8DeltXRtJocF58yoqo8lRTYGNfSsuEe2Ohx9QDSmoMHze3gMNCCG4pSTIf6Y3EL1EThbApkBkwaoSslX3PGSpQDkIHiLt13mqHcqkFi9A4xXxGqqm1m2BgMFzO3s0x4gKKQGwNkPkHabuFu14sXd9hrSphO2c8KlCzOqPeU-w-y5u_9IIuxGZq__eKfFV_62_T4HeD0dmJMFC2UfgZ882sxmZHnL-uOEP5YnE3o7t5AONcmHw_Z7vjBBgduKhf50DUcalvTTqvw6lQ2TCgBO9PtLyqs.plweGNd6N-1LRxCnAQhXvQL0oHbtKgEi0Y1MsQ8FVLE&dib_tag=se&keywords=data%2Banalyst%2Btshirt&qid=1765918177&s=apparel&sr=1-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&customId=B0752XJYNL&customizationToken=MC_Assembly_1%23B0752XJYNL&th=1&psc=1"

    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/127.0.0.0 Safari/537.36"
        ),
        "Accept-Language": "en-US,en;q=0.9",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Referer": "https://www.google.com/",
        "Connection": "keep-alive",
    }

    # send request as if it's Chrome browser
    page = requests.get(url, headers=headers)

    soup1 = BeautifulSoup(page.content, 'html.parser') 

    soup2 = BeautifulSoup(soup1.prettify(), 'html.parser') 

    title = soup2.find('span', id = 'productTitle').text

    price = soup2.find(class_ = 'a-price-whole').text

    price = price.replace('\n', '').replace('\t', '').replace(',', '').strip()
    
    title = title.strip()

    import datetime

    today = datetime.date.today()

    import csv

    header = ['Title', 'Price','Date']
    
    data  = [title, price, today] 

    with open('AmazonWebscraperDataset.csv', 'a+', newline = '', encoding = 'UTF8')  as f:
        writer = csv.writer(f)
        writer.writerow(data)

In [16]:
while(True):
    check_price()
    time.sleep(5)

KeyboardInterrupt:

In [17]:
import pandas as pd

df = pd.read_csv(r"C:\Users\HP\AmazonWebscraperDataset.csv")
df

,Title,Price,Date
0,Data Analyst Funny Athletic Lettering Data Ana...,28611 .,2026-01-05
1,Data Analyst Funny Athletic Lettering Data Ana...,28611 .,2026-01-05
2,Data Analyst Funny Athletic Lettering Data Ana...,28611 .,2026-01-05